#!/usr/bin/env bash
#
# build-ubuntu-fips.sh — Ubuntu 20.04 / 22.04 / 24.04 FIPS build.
#
# Wraps ubuntu-fips/<version>/build.sh, which already uses BuildKit
# `--secret id=pro-attach-config,src=…`. Our contribution here is:
#   1. Point --secret at $CREDS_DIR/pro-attach-config.yaml (generated by
#      materialize_credentials.sh from the workflow's UBUNTU_PRO_TOKEN
#      input) instead of the committed template with REPLACE_WITH_TOKEN.
#   2. Set the ENABLE_STIG / SKIP_STIG_BANNER env vars from workflow inputs.
#   3. Save the built image as an artifact.

set -euo pipefail

: "${MATRIX_VERSION:?}"       # 20.04 / 22.04 / 24.04
: "${CREDS_DIR:?}"
: "${PE_VERSION:?}"

version="$MATRIX_VERSION"
codename=""
case "$version" in
    20.04) codename="focal" ;;
    22.04) codename="jammy" ;;
    24.04) codename="noble" ;;
    *) echo "::error::Unsupported Ubuntu FIPS version: $version"; exit 1 ;;
esac

image_tag="${IMAGE_REGISTRY:+$IMAGE_REGISTRY/}ubuntu-${codename}-fips:${PE_VERSION}${CUSTOM_TAG:+-$CUSTOM_TAG}"
build_label="canvos.build=${MATRIX_OS}-${MATRIX_VERSION}"

export DOCKER_BUILDKIT=1

# Ubuntu 20.04 has a plain "Dockerfile"; 22.04 and 24.04 have
# Dockerfile.ubuntu<version>-fips. Match that.
case "$version" in
    20.04)
        dockerfile="ubuntu-fips/20.04/Dockerfile"
        build_context="ubuntu-fips/20.04"
        ;;
    22.04|24.04)
        dockerfile="ubuntu-fips/${version}/Dockerfile.ubuntu${version}-fips"
        build_context="ubuntu-fips"   # 22/24 build context is the parent dir
        ;;
esac

# The pro-attach-config.yaml token comes from $CREDS_DIR (generated on the
# fly from UBUNTU_PRO_TOKEN), NOT from the committed template.
docker build \
    --secret id=pro-attach-config,src="$CREDS_DIR/pro-attach-config.yaml" \
    --build-arg ENABLE_STIG="${UBUNTU_FIPS_ENABLE_STIG:-true}" \
    --build-arg SKIP_STIG_BANNER="${UBUNTU_FIPS_SKIP_STIG_BANNER:-false}" \
    --label "$build_label" \
    -t "$image_tag" \
    -f "$dockerfile" \
    "$build_context"

mkdir -p build
docker save "$image_tag" | gzip > "build/ubuntu-${codename}-fips.tar.gz"

if [ -n "${IMAGE_REGISTRY:-}" ]; then
    docker push "$image_tag"
fi
