VERSION 0.6
FROM alpine

ARG K3S_VERSION=1.25.2
ARG SPECTRO_VERSION=3.3.3
ARG SPECTRO_LUET_VERSION=1.0.3
ARG KAIROS_VERSION=1.5.0
ARG OS_FLAVOR=ubuntu
ARG OS_VERSION=22
ARG IMAGE_REPOSITORY=3pings
ARG K8S_FLAVOR=k3s
ARG K8S_FLAVOR_TAG="-k3s1"
ARG K8S_PROVIDER_VERSION="v1.1.3"

docker:
    # IF [ "$OS_FLAVOR" = "ubuntu-20-lts" ] || [ "$FLAVOR" = "ubuntu-22-lts" ] || [ "$FLAVOR" = "ubuntu" ]
    FROM DOCKERFILE -f base_images/Dockerfile.ubuntu .
    
    ARG K3S_VERSION=${K3S_VERSION}
    ARG SPECTRO_VERSION=${SPECTRO_VERSION}
    ARG SPECTRO_LUET_VERSION=${SPECTRO_LUET_VERSION}
    ARG KAIROS_VERSION=${KAIROS_VERSION}
    ARG OS_FLAVOR=${OS_FLAVOR}
    ARG OS_VERSION=${OS_VERSION}
    ARG IMAGE_REPOSITORY=${IMAGE_REPOSITORY}
    ARG K8S_FLAVOR=${K8S_FLAVOR}
    ARG K8S_FLAVOR_TAG=${K8S_FLAVOR_TAG}
    ARG K8S_PROVIDER_VERSION=${K8S_PROVIDER_VERSION}
    
    SAVE IMAGE go-example:latest