#cloud-config
users:
  - name: kairos
    passwd: kairos

install:
  partitions:
    oem:
      size: 5000
      fs: ext4

stages:
  initramfs:
    - if: '[ ! -f "/run/cos/live_mode" ]'
      name: link agent provider stylus
      commands:
        - echo "Linking agent provider"
        - mkdir -p /usr/local/bin/
        - ln -sf /opt/spectrocloud/bin/agent-provider-stylus /usr/local/bin/agent-provider-stylus
  after-install:
    - name: uki stylus unpack
      commands:
        - echo "Copying files to persistent path"
        - umount /oem || true
        - umount /usr/local || true
        - for p in $(ls /dev/mapper/vda*); do cryptsetup close $p; done
        - /usr/lib/systemd/systemd-cryptsetup attach persistent $(findfs PARTLABEL=persistent) - tpm2-device=auto
        - /usr/lib/systemd/systemd-cryptsetup attach oem $(findfs PARTLABEL=oem) - tpm2-device=auto
        - mount /dev/mapper/persistent /usr/local
        - mount /dev/mapper/oem /oem
        - mkdir -p /usr/local/.state/opt.bind/spectrocloud/bin
        - mkdir -p /usr/local/bin/
        - mkdir -p /oem/opt.bind
        - cp -rfv /run/initramfs/live/luet /usr/local/bin/
        - cp -rfv /run/initramfs/live/stylus-image.tar /usr/local/
        - cp -rfv /run/initramfs/live/stylus-image.tar /oem/opt.bind/
        - luet util unpack file://usr/local/stylus-image.tar /
        - cp -rfv /opt/spectrocloud/ /usr/local/.state/opt.bind/
        - umount /dev/mapper/persistent
        - umount /dev/mapper/oem
        - cryptsetup close /dev/mapper/persistent
        - cryptsetup close /dev/mapper/oem
  after-reset:
    - name: "Copy files from oem to persistent"
      commands:
        - echo "Copying files back to persistent path"
        - umount /oem || true
        - umount /usr/local || true
        - for p in $(ls /dev/mapper/vda*); do cryptsetup close $p; done
        - /usr/lib/systemd/systemd-cryptsetup attach persistent $(findfs PARTLABEL=persistent) - tpm2-device=auto
        - /usr/lib/systemd/systemd-cryptsetup attach oem $(findfs PARTLABEL=oem) - tpm2-device=auto
        - mount /dev/mapper/persistent /usr/local
        - mount /dev/mapper/oem /oem
        - mkdir -p /usr/local/.state/opt.bind/spectrocloud/bin
        - mkdir -p /usr/local/bin/
        - mkdir -p /oem/opt.bind
        - mkdir -p /usr/local/.state/opt.bind/spectrocloud/bin
        - luet util unpack file://oem/opt.bind/stylus-image.tar /
        - umount /dev/mapper/persistent
        - umount /dev/mapper/oem
        - cryptsetup close /dev/mapper/persistent
        - cryptsetup close /dev/mapper/oem
