#cloud-config
users:
  - name: kairos
    passwd: kairos

stages:
  after-install:
    - commands:
        - echo "Copying files to persistent path"
        - /usr/lib/systemd/systemd-cryptsetup attach persistent $(findfs PARTLABEL=persistent) - tpm2-device=auto
        - mount /dev/mapper/persistent /usr/local
        - mountpoint="/usr/local" && ! findmnt -rno TARGET "$mountpoint" > /dev/null && mount /dev/mapper/persistent "$mountpoint" || echo "Already mounted."
        - mkdir -p /usr/local/bin/
        - cp -rfv /run/initramfs/live/luet /usr/local/bin/
        - luet util unpack file:///run/initramfs/live/stylus-image.tar /
