#cloud-config
stages:
  boot:
    - name: "remove ubuntu rootfs partition"
      commands:
        - |
          # Find the partition with UBUNTU_ROOTFS label
          UBUNTU_PARTITION=$(blkid -L UBUNTU_ROOTFS 2>/dev/null || true)
          if [ -n "$UBUNTU_PARTITION" ]; then
            echo "Found Ubuntu rootfs partition: $UBUNTU_PARTITION"
            # Get the partition number
            # Handle both standard (/dev/sda5) and NVMe (/dev/nvme0n1p5) formats
            if [[ "$UBUNTU_PARTITION" =~ ^/dev/nvme[0-9]+n[0-9]+p[0-9]+$ ]]; then
              # NVMe format: /dev/nvme0n1p5
              UBUNTU_PART_NUM=$(echo "$UBUNTU_PARTITION" | grep -oE '[0-9]+$')
              DISK_DEV=$(echo "$UBUNTU_PARTITION" | sed 's/p[0-9]*$//')
            else
              # Standard format: /dev/sda5
              UBUNTU_PART_NUM=$(echo "$UBUNTU_PARTITION" | grep -oE '[0-9]+$')
              DISK_DEV=$(echo "$UBUNTU_PARTITION" | sed 's/[0-9]*$//')
            fi
            
            echo "Wiping filesystem signatures from Ubuntu partition: $UBUNTU_PARTITION"
            # Wipe filesystem signatures before deleting the partition
            if command -v wipefs >/dev/null 2>&1; then
              wipefs -a "$UBUNTU_PARTITION" || echo "Warning: Failed to wipe filesystem signatures from $UBUNTU_PARTITION"
            else
              echo "Warning: wipefs command not found, skipping filesystem signature wipe"
            fi
            
            echo "Removing Ubuntu partition $UBUNTU_PART_NUM from $DISK_DEV"
            # Remove the Ubuntu partition - Kairos will handle the remaining space allocation
            parted -s "$DISK_DEV" rm "$UBUNTU_PART_NUM" || echo "Failed to remove partition $UBUNTU_PART_NUM"
            echo "Ubuntu rootfs partition removed - Kairos will create state and persistent partitions with remaining space"
          else
            echo "No Ubuntu rootfs partition found with label UBUNTU_ROOTFS"
          fi
  network:
    - if: '[ -f "/run/cos/active_mode" ]'
      name: "extract content from content partition"
      commands:
        - bash /opt/spectrocloud/scripts/maas-content.sh