#cloud-config
stages:
  boot:
    - name: "remove ubuntu rootfs partition"
      commands:
        - |
          # Find the partition with UBUNTU_ROOTFS label
          UBUNTU_PARTITION=$(blkid -L UBUNTU_ROOTFS 2>/dev/null || true)
          if [ -n "$UBUNTU_PARTITION" ]; then
            echo "Found Ubuntu rootfs partition: $UBUNTU_PARTITION"
            # Get the partition number
            UBUNTU_PART_NUM=$(echo "$UBUNTU_PARTITION" | sed 's/.*[^0-9]\([0-9]\+\)$/\1/')
            # Get the disk device (remove partition number)
            DISK_DEV=$(echo "$UBUNTU_PARTITION" | sed 's/[0-9]\+$//')
            
            echo "Removing Ubuntu partition $UBUNTU_PART_NUM from $DISK_DEV"
            # Remove the Ubuntu partition - Kairos will handle the remaining space allocation
            parted -s "$DISK_DEV" rm "$UBUNTU_PART_NUM" || echo "Failed to remove partition $UBUNTU_PART_NUM"
            echo "Ubuntu rootfs partition removed - Kairos will create state and persistent partitions with remaining space"
          else
            echo "No Ubuntu rootfs partition found with label UBUNTU_ROOTFS"
          fi