#cloud-config
install:
 device: /dev/sda
 reboot: true
 poweroff: false
stylus:
 debug: true
 site:
  paletteEndpoint: xxxx.spectrocloud.com
  autoRegister: true
  edgeHostToken: xxxxxxxxxxx
  insecureSkipVerify: false

stages:
  initramfs:
    - name: "Set user and password"
      users:
        kairos:
          passwd: "kairos"
          groups:
            - "admin"