ARG CLI_IMAGE
ARG ARCH
FROM --platform=linux/${ARCH} ${CLI_IMAGE} AS validate-user-data

RUN chmod +x /usr/local/bin/palette-edge-cli

COPY . /tmp/context

RUN mkdir -p /validated && \
    if [ -f /tmp/context/user-data ]; then \
        /usr/local/bin/palette-edge-cli validate -f /tmp/context/user-data && \
        cp /tmp/context/user-data /validated/config.yaml; \
    else \
        echo "user-data file does not exist (skipping validation)"; \
    fi; \
    rm -rf /tmp/context