name: Pr

on: [pull_request]

concurrency:
  group: pr-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: read
  checks: write

jobs:
  k8s:
    name: k8s install test
    uses: ./.github/workflows/build.yaml
    strategy:
      matrix:
        flavor: [k3s, kubeadm, rke2]
    with:
      target: build-provider-images
      branch: ${{ github.head_ref }}
      envs: |
        TARGET=install-k8s
        K8S_DISTRIBUTION=${{ matrix.flavor }}
        ARCH=amd64
