# name: Pr

# on: [pull_request]

# concurrency:
#   group: ${{ github.pr_workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# permissions:
#   contents: read

# jobs:
#   build: 
#     uses: ./.github/workflows/release.yaml
#     secrets: inherit