name: Test Dispatch
on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test input'
        required: false
        type: string
        default: 'hello'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Input was ${{ github.event.inputs.test_input }}"